# Generated by Django 4.1.1 on 2022-09-28 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tonika', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tonika.author'),
            preserve_default=False,
        ),
    ]
